### ISSUE TITLE
Relicense Bio-Formats examples as BSD-2

### ISSUE THREAD

**Issue by sbesson** [ome/bio-formats-examples#81]
See https://github.com/ome/www.openmicroscopy.org/issues/514 for the original discussion

LIke other OME projects, the goal of the Bio-Formats examples maintained in this repository is to illustrate the usage of the API in a manner that makes it as re-usable as possible in documentation, tutorials.

To achieve this, this issue proposes to relicense this component from the current GPL-2 to BSD-2. In addition to the source code relicensing, the project dependency could be simply reduced to `formats-bsd`.

The list of developers who have made significant contributions to the source files has been computed from ` git log --pretty=format:"%an%x09" --follow src/main/ | sort | uniq`:

- [x] @sbesson
- [x] @dgault 
- [x] @jburel 
- [x] @rleigh-codelibre 
- [x] @melissalinkert 
- [x] @jamesmyatt 

Could everyone confirm they are happy for their contributions to be relicensed under the terms of the BSD-2 license?

**Comment by sbesson** [comment]
I authorize my contributions to bio-formats-examples to be relicensed as BSD-2.

**Comment by rleigh-codelibre** [comment]
All my contributions to this repository are owned by the University of Dundee since they were all made while working for OME.

**Comment by jamesmyatt** [comment]
I can confirm that I'm happy with this.

**Comment by jamesmyatt** [comment]
In fact, I only contributed a minor bug fix, so, for future reference, I'm happy to assign all copyright to the project. https://github.com/ome/bio-formats-examples/pull/39

**Comment by dgault** [comment]
I can confirm I am happy with this
